
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
crafty = { path = "../game", default-features = false }

[features]
default = ["crafty/default"]
dylib-engine = ["crafty/dylib-engine"]
