
[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
crafty = { path = "../game", optional = true }

[features]
default = ["crafty"]
dylib = ["fyrox/dylib"]
